### ISSUE TITLE
Creeaza pachet pentru proiectul tau

### ISSUE THREAD

**Issue by DanBrezeanu** [mariaaliu/HiPlan#1]
Asa cum importi, de exemplu, `json`, asa poti sa-ti importi propriul proiect.
De exemplu: 
`from hiplan.app import Record`

Crearea unui pachet ajuta mult la readability si usureaza import-urile.

How to:
1. Creeaza un `setup.py` in root-ul proiectului
```python
import setuptools

setuptools.setup(
    name="hiplan",
    version="0.0.1",
    author="<COMPLETE HERE>",
    author_email="<COMPLETE HERE>",
    description="<COMPLETE HERE>",
    url="https://github.com/<COMPLETE HERE>",
    project_urls={
        "Bug Tracker": "https://github.com/<COMPLETE HERE>/issues",
    },
    packages=setuptools.find_packages(),
    python_requires=">=3.6",
)
```
2. Muta toate fisierele sursa (*.py) existente intr-un director care sa se numeasca ca si modulul (de preferat `hiplan`)
3. Creeaza un `__init__.py` in fiecare director care vrei sa fie un modul (a.k.a sa fie importabil)
4. Intstaleaza pachetul (in mod editabil de preferat) din root-ul proiectului
        `pip3 install -e hiplan` 
5. Testeaza
 ```bash
    python3 -c "import hiplan"
  ```

**Comment by mariaaliu** [comment]
Am creat setup.py in directorul HiPlan (directorul proiectului) si am copiat codul de mai sus in fisier.
Am creat un director hiplan in HiPlan si am mutat app.py in el.
Nu inteleg cum ar trebui sa creez __init__.py. Doar creez un fisier cu numele asta si stie Python ce sa faca?
Si ar trebui creez __init__.py doar in hiplan?

**Comment by mariaaliu** [comment]
Am incercat sa ii dau comanda: pip3 install -e hiplan  ,dar mi-a spus:

Command 'pip3' not found, but can be installed with:

sudo apt install python3-pip  ,
asa ca am incercat ce mi-a sugerat el si a tot instalat si updatat chestii si dupa mi-a dat eroarea asta:
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-66.74_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by DanBrezeanu** [comment]
> Am creat setup.py in directorul HiPlan (directorul proiectului) si am copiat codul de mai sus in fisier.
> Am creat un director hiplan in HiPlan si am mutat app.py in el.
> Nu inteleg cum ar trebui sa creez **init**.py. Doar creez un fisier cu numele asta si stie Python ce sa faca?
> Si ar trebui creez **init**.py doar in hiplan?

Da, stie Python ce sa faca. Cand vede `__init__.py` intr-un director, stie sa faca acel director un modul (adica sa fie importabil). De ex daca ai 
```
dir1
|----- __init__.py
|----- dir2
        |-----  __init__.py
        |-----  example.py
```

O sa poti sa dai
`from dir1.dir2 import example`
sau
`import dir1`

**Comment by DanBrezeanu** [comment]
> Am incercat sa ii dau comanda: pip3 install -e hiplan ,dar mi-a spus:
> 
> Command 'pip3' not found, but can be installed with:
> 
> sudo apt install python3-pip ,
> asa ca am incercat ce mi-a sugerat el si a tot instalat si updatat chestii si dupa mi-a dat eroarea asta:
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-66.74_amd64.deb 404 Not Found [IP: 91.189.88.152 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Incearca sa dai
`sudo apt-get update --fix-missing`

**Comment by mariaaliu** [comment]
Am testat ce am facut cu comanda python3 -c "import hiplan" si nu se intampla nimic.

**Comment by DanBrezeanu** [comment]
> Am testat ce am facut cu comanda python3 -c "import hiplan" si nu se intampla nimic.

Daca nu iti da eroare, inseamna ca merge, ca a reusit sa importe `hiplan`
