### ISSUE TITLE
Kivy Setup

### ISSUE THREAD

**Issue by DanBrezeanu** [mariaaliu/HiPlan#12]
Avem de facut si setup-ul pentru Kivy. Pana atunci mai exista niste pasi.
Cand instalezi ceva cu `pip3 install`, instalarea se face system-wide, adica toate proiectele vor folosi aceleasi versiuni de pachete. Ne propunem sa izolam fiecare proiect cu dependintele sale. Pentru acest scop se foloseste un "virtual environment". Avand in vedere ca proiectul de Kivy o sa trebuiasca rulat in Windows, iti sugerez prima oara sa instalam Python si in Windows.

1. [Instaleaza](https://www.python.org/downloads/) Python
     - Bifeaza "Add Python installation to PATH" (sau ceva in genul)
     - Bifeaza "Extend PATH past the 256 character limit" (again, sau ceva de genul)
2. Verifica instalarea
     - Windows Key + R   -> Scrie "cmd"   -> Enter
     - Se va deschide un Command Prompt (terminal de Windows)
     - Scrie comanda "py" si ar trebui sa se deschida un terminal interactiv de python (Ctr + Z    Enter ca sa iesi    sau   `exit()`)
3. Instaleaza `pip`
    - Ia cu copy-paste ce este [aici](https://bootstrap.pypa.io/get-pip.py) si pune-l intr-un fisier .py undeva in Windows (Desktop, Downloads etc.) 
    - Deschide un cmd (Command Prompt) in acea locatie
      - Cea mai usoara varianta este sa deschizi File Explorer in acea locatie si in bara de sus (unde este Path-ul catre acel director) sa scrii "cmd" si sa dai enter ([picture](https://user-images.githubusercontent.com/33134460/114980583-5814b580-9e95-11eb-8b79-5d01f2ba2afd.png))
    - Ruleaza comanda `py <numele_script_ului_dat_cu_copy_paste>` (ex: `py get-pip.py`)
    - Verifica instalarea: `pip3 --version` sau `py -m pip --version`
4. Instaleaza pachetul pentru Virtual Environment
    - `py -m pip install venv`
5. Creeaza un virtual environment in proiect
   - Du-te in root-ul proiectului
   - Deschide un `cmd` (sau foloseste Terminal din VSCode: pentru asta trebuie sa deschizi directorul in VSCode cu Windows (right-click in file exploer -> "Open with Code")
   - Ruleaza `py -m venv env` (dureaza vreo 2 min)
   - Ar trebui sa existe acum un director numit "env"
6. Activeaza environmentul
   - In `cmd`: `.\env\Scripts\activate.bat`
   - Daca ai deschis in VSCode si folosesti terminalul de acolo, VSCode deschide by default un PowerShell care este un terminal de Windows cu mai multe feature-uri. Ca sa activezi virtual environment-ul in PS (PowerShell) ruleaza `.\env\Scripts\Activate.ps1`
   - Ar trebui sa se schimbe promptul putin cu un `(env)` inainte ([picture](https://user-images.githubusercontent.com/33134460/114981389-98286800-9e96-11eb-90a5-d7b67461d94f.png))
7. Instaleaza pachetele necesare
`python -m pip install kivy_deps.sdl2 kivy_deps.glew kivy_deps.angle`
`python -m pip install kivy kivy_examples`
8. Verifica instalarea
`python .\env\share\kivy-examples\demo\showcase\main.py`
   - Daca da o eroare de genul `[CRITICAL] [App ] Unable to get a Window, abort.` incearca sa dai urmatorele comenzi
        ```
        set USE_SDL2=1
        set USE_GSTREAMER=1
        ```
9. Genereaza `requirements.txt`: pentru a stii si alti oameni ce pachete am folosit, se genereaza un fisier cu toate pachetele instalate in acest virtual environment:
       `python -m pip freeze > requirements.txt`
       
10. Adauga in repo `requirements.txt` pe un branch pentru acest issue
11. De fiecare data cand te reapuci de lucrat ar trebui sa tii minte sa activezi virtual environment-ul (pasul 6). Recomand terminalul din VSCode pentru a nu-ti bate prea tare capul in general

**Comment by mariaaliu** [comment]
La pasul 4 imi spune: 
ERROR: Could not find a version that satisfies the requirement venv
ERROR: No matching distribution found for venv
