### ISSUE TITLE
Serialize & Deserialize

### ISSUE THREAD

**Issue by DanBrezeanu** [mariaaliu/HiPlan#3]
Completeaza functiile de `serialize` pentru a include toate detaliile claselor. Cand serializezi `enum`-uri foloseste `.value` cand introduci in dictionar. La fel, grija la `datetime`  (hint: `strftime`, `isoformat`)

Scrie functiile de deserialize pentru a transforma un JSON citit de App intr-o ierarhie de obiecte:
Exemplu:
```python
json_citit = """{
   "boards": [
          {
             "name": "FirstBoard"
             "records": [ 
                 {
                      "name": "FirstRecord"
                      "tasks:" [
                           {
                              "title":  "MyFirstTask"
                              "description": "This is my first task"
                            }
                      ]
                 }
             ]
          }
   ]
}"""

# Citeste json-ul, il parseaza (`json.loads) si instantiaza obiectele
a = App.deserialize(json_citit)
len(a.boards)         # 1
len(a.boards[0].records)    # 1
len(a.boards[0].records[0].name)    # FirstRecord 
```

Nu uita ca functia deserialize trebuie sa fie statica pentru fiecare clasa (`@staticmethod` si nu se pune `self` in parametri)

**Comment by DanBrezeanu** [comment]
Inainte sa te apuci sa creezi branch-ul:
1. Fii sigura ca esti pe `master`: `git checkout master`
2. Fii sigura ca master-ul tau (local) este updatat (sincronizat cu master-ul de pe remote): `git pull origin master`

**Comment by mariaaliu** [comment]
Am facut partea de serialize si am testat-o pt deadline = datetime.now() si merge.
Dar nu stiu ce sa fac in cazul in care deadline e None, pentru ca atunci self.deadline.strftime("%m/%d/%Y, %H:%M:%S") da eroare.

**Comment by DanBrezeanu** [comment]
> Am facut partea de serialize si am testat-o pt deadline = datetime.now() si merge.
> Dar nu stiu ce sa fac in cazul in care deadline e None, pentru ca atunci self.deadline.strftime("%m/%d/%Y, %H:%M:%S") da eroare.

O sa dea eroare pentru ca `self.deadline` este None si incerci sa faci `None.strftime` care evident nu exista.
Echivalentul lui None in JSON este `null` (incearca `json.dumps({'a': None})`). Asa ca inainte sa faci `self.deadline.strftime`, incearca sa  verifici daca self.deadline nu este None (pentru a face intr-o linie si a fi relativ clean, foloseste `or`)
